# Generated by Django 5.2.1 on 2025-06-03 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0019_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.BigIntegerField(unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=24)),
                ('raw_response', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tbank_payment', to='store.order')),
            ],
            options={
                'verbose_name': 'Платёж T-Bank',
                'verbose_name_plural': 'Платежи T-Bank',
                'ordering': ('-created',),
            },
        ),
    ]
