# Generated by Django 5.1.7 on 2025-04-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_color_size_product_additional_info_product_colors_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="back_image",
        ),
        migrations.AddField(
            model_name="product",
            name="front_image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
