# Generated by Django 5.2 on 2025-04-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productimage_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_main', 'id']},
        ),
    ]
