# Generated by Django 5.2 on 2025-05-02 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, help_text='Если процентная — в диапазоне 0–100, иначе в валюте.', max_digits=5)),
                ('type', models.CharField(choices=[('percent', 'Процентная скидка'), ('fixed', 'Фиксированная сумма')], default='percent', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, help_text='До какого момента действует.', null=True)),
            ],
        ),
    ]
