# Generated by Django 5.2 on 2025-05-03 15:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_user_alter_promocode_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='telegram',
            field=models.CharField(blank=True, help_text='username без @', max_length=64, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Улица, дом, кв.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='RU', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона (только цифры, 7‑15 символов).', regex='^\\+?[0-9]{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, max_length=15, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('courier', 'Курьер (600\xa0₽)'), ('yandex', 'Пункт‑выдачи Яндекс'), ('cdek', 'Пункт‑выдачи СДЭК')], default='courier', max_length=20, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.DecimalField(decimal_places=2, help_text='Если процентная —\xa00‑100, иначе сумма в рублях.', max_digits=5),
        ),
    ]
