# Generated by Django 5.2.1 on 2025-06-03 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона (только цифры, 7-15 символов).', regex='^\\+?[0-9]{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('courier', 'Курьер (600 ₽)'), ('yandex', 'Пункт-выдачи Яндекс'), ('cdek', 'Пункт-выдачи СДЭК')], default='courier', max_length=20, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.DecimalField(decimal_places=2, help_text='Если процентная — 0-100, иначе сумма в рублях.', max_digits=5),
        ),
    ]
