# Generated by Django 5.2 on 2025-05-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Код')),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, help_text='Если задать, то это процент от суммы заказа.', null=True, verbose_name='Скидка %')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Если задана, то фиксированная сумма в рублях.', max_digits=10, null=True, verbose_name='Скидка ₽')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
