# Generated by Django 5.2 on 2025-05-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
