"""
Django settings for myshop project.
Generated by 'django-admin startproject' using Django 5.1.7.
"""
from pathlib import Path

# ──────────────────────────────────────────────────────────────────────────────
# Paths & base
# ──────────────────────────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent

# ──────────────────────────────────────────────────────────────────────────────
# Security
# ──────────────────────────────────────────────────────────────────────────────
SECRET_KEY = "django-insecure-ny3r#_(m=0m_)$ll^(-n7yn(mv%g3bh%akn1%((h!2=u8w+ww0"
DEBUG = True
ALLOWED_HOSTS: list[str] = []

# ──────────────────────────────────────────────────────────────────────────────
# Applications
# ──────────────────────────────────────────────────────────────────────────────
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "checkout", # оплата
    "store",      # наш магазин
    "accounts",   # кастомный пользователь
]

# ──────────────────────────────────────────────────────────────────────────────
# Middleware / root urls / WSGI
# ──────────────────────────────────────────────────────────────────────────────
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "myshop.urls"
WSGI_APPLICATION = "myshop.wsgi.application"

# ──────────────────────────────────────────────────────────────────────────────
# Templates
# ──────────────────────────────────────────────────────────────────────────────
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],      # <project_root>/templates/
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cart.context_processors.cart_totals",
            ],
        },
    },
]

# ──────────────────────────────────────────────────────────────────────────────
# Database
# ──────────────────────────────────────────────────────────────────────────────
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "myshopdb",
        "USER": "muslim",
        "PASSWORD": "timanice1027",
        "HOST": "localhost",
        "PORT": "5432",
    }
}

# ──────────────────────────────────────────────────────────────────────────────
# Password validation
# ──────────────────────────────────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ──────────────────────────────────────────────────────────────────────────────
# Internationalization
# ──────────────────────────────────────────────────────────────────────────────
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ──────────────────────────────────────────────────────────────────────────────
# Static & media
# ──────────────────────────────────────────────────────────────────────────────
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ──────────────────────────────────────────────────────────────────────────────
# Custom user model
# ──────────────────────────────────────────────────────────────────────────────
AUTH_USER_MODEL = "accounts.User"

# ──────────────────────────────────────────────────────────────────────────────
# Auth redirects
# ──────────────────────────────────────────────────────────────────────────────
LOGIN_REDIRECT_URL  = "/"      # после успешного логина
LOGOUT_REDIRECT_URL = "home"   # после выхода → главная

# ──────────────────────────────────────────────────────────────────────────────
# Email backend (console для разработки)
# ──────────────────────────────────────────────────────────────────────────────
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "no-reply@myshop.local"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = [
    "accounts.backends.EmailPhoneUsernameBackend",   # кастомный
    "django.contrib.auth.backends.ModelBackend",     # стандартный
]

# ──────────────────────────────────────────────────────────────────────────────
# Корзина
# ──────────────────────────────────────────────────────────────────────────────
CART_SESSION_KEY = "cart" 

# ──────────────────────────────────────────────────────────────────────────────
# Платежный шлюз
# ──────────────────────────────────────────────────────────────────────────────
YOOKASSA_SHOP_ID = "<ваш_shop_id>"
YOOKASSA_SECRET_KEY = "<ваш_секретный_ключ>"